version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"    
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/paulo/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network      

networks: 
    mongo-compose-network:
      driver: bridge